steps:
  # 1. Deploy the backend service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Backend'
    args:
      - 'run'
      - 'deploy'
      - 'aistory' # Corrected service name
      - '--source'
      - './backend' # Deploy from the backend directory
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--project'
      - '${_PROJECT_ID}'

  # 2. Get the URL of the deployed backend service
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Get Backend URL'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services describe aistory \
          --platform managed \
          --region asia-northeast1 \
          --format 'value(status.url)' > backend_url.txt

  # 3. Build the Next.js frontend
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build Frontend'
    args: ['install']
    dir: 'frontend'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'frontend'

  # 4. Replace the placeholder URL in the frontend script
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Update Frontend URL'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s|http://localhost:3000|$(cat backend_url.txt)|g" frontend/src/app/page.tsx

  # 5. Create the Cloud Storage bucket if it doesn't exist
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create GCS Bucket'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud storage buckets create gs://aistory-frontend-neocore-f43f5 --location=asia-northeast1 --project=${_PROJECT_ID} || echo "Bucket already exists"

  # 6. Upload the frontend files to the bucket
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Upload Frontend'
    args:
      - 'storage'
      - 'cp'
      - '-r'
      - 'frontend/out/*'
      - 'gs://aistory-frontend-neocore-f43f5/'

  # 7. Make the frontend files publicly accessible
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Make Frontend Public'
    args:
      - 'storage'
      - 'iam'
      - 'ch'
      - 'allUsers:objectViewer'
      - 'gs://aistory-frontend-neocore-f43f5'

  # 8. Set the main page for the website
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Set Main Page'
    args:
      - 'storage'
      - 'buckets'
      - 'update'
      - 'gs://aistory-frontend-neocore-f43f5'
      - '--web-main-page-suffix=index.html'

substitutions:
  _PROJECT_ID: 'neocore-f43f5'

options:
  logging: CLOUD_LOGGING_ONLY
